---
title: "Peer Review durch einen Review Report"
output: 
  html_document:
    theme: cosmo
    code_download: true
    code_folding: hide
    toc: true
    toc_float: true
---

# Was ist ein Peer Review?

In ihrem Peer Review sollten Sie die Arbeit ihrer Kommilitonen bewerten und kritisch hinterfragen.
Jeder Projektkursteilnehmer bekommt zufällig die Ausarbeitung des Projekts einer anderen Gruppe zugewiesen.

Ihre Aufgabe ist es nun, dieses Projekt zu lesen und die Ergebnisse, vor allem Beschreibungen und Interpretationen, kritisch zu hinterfragen und Verbesserungen an der Ausarbeitung anzuregen.

Ziele des Review Reports:

- Die Gruppe mit deren Arbeit Sie sich auseinandersetzen sollte durch ihre Feedback _Hinweise erhalten_, wo die Stärken und vor allem auch Schwächen ihrer Arbeit lagen und wie Sie diese beim nächsten Projekt vermeiden kann
- Sie selbst können durch die Auseinandersetzung mit der Arbeit einer anderen Gruppe neue Ideen sammeln, wie bestimmte Sachverhalte dargestellt werden können und bekommen einen ganz neuen Blick auf ihre eigene Ausarbeitung

Durch die Review Reports sollen Sie sich gegenseitig **helfen**! Bitte versuchen Sie in ihren Reports _nicht nett_, sondern _kritisch und konstruktiv_ zu sein! Dies ist sowohl für Sie als auch für die andere Gruppe wichtig!

# Anonymität

Sie führen den Peer-Review im sogenannten Double-Blind-Verfahren durch. D.h. weder Sie wissen welche Gruppe die Projektarbeit verfasst hat, noch weiß die Gruppe später, wer den Review Report verfasst hat.

- Bitte geben Sie _konstruktives_ Feedback und sparen Sie nicht mit Kritik! Nur durch Kritik und den Hinweis auf Fehler können sich die Gruppen verbessern
- Bitte werden Sie in ihrem **Feedback nicht beleidigend**! Grundsätzlich gilt: Schreiben Sie nichts, was Sie nicht auch der Gruppe persönlich sagen würden.

# Aufbau des Peer Review Reports

1. Starten Sie mit einer _kurzen Zusammenfassung_ der Arbeit die Sie reviewen sollen, gehen Sie hierbei auf die Idee des Projekts, die Hauptargumente und die gefunden Ergebnisse ein.
2. Anschließend sollten Sie auf die positiven Aspekte der vorliegenden Projektarbeit eingehen. Stellen Sie gute Grafiken, Interpretationen etc. heraus. 
3. Im Anschluss sollten Sie ihre Kritik an der vorliegenden Arbeit formulieren. Greifen Sie die Hauptpunkte der Autoren auf und überlegen Sie, ob diese Argumente in dem Projekt ihrer Meinung nach so angebracht werden können. 
    - Gestalten Sie ihre Kritik _konstruktiv_ indem Sie alternative Darstellungen und/oder Interpretationen vorschlagen


# Fragen die Sie im Review Report aufgreifen und beantworten sollten

**Zusammenfassung:**

- Was ist die Hauptaussage der Projektarbeit? Was lernen Sie aus der vorliegenden Projektarbeit? 

**Positive Aspekte:**

- Welche drei Punkte sind besonders gut gelungen?

Stützen Sie sich in ihrem Text auf folgende Elemente:

- Qualität Schaubilder (Legende, Überschrift, Visualisierung insgesamt, …) und Tabellen (Nachkommastellen, Beschriftung, …)
- Interpretation der Schaubilder und Tabellen / Ergebnisse nachvollziehbar? 
- Nennen Sie konkrete Stellen, um ihre Argumente zu unterstützen 
- Gehen Sie auf Struktur, Klarheit und Verständlichkeit ein

**Potential für Verbesserungen:**

- Welche drei Punkte sollten die Autoren noch verbessern, um ihren Projektarbeit aufzuwerten?

Stützen Sie sich in ihrem Text auf folgende Elemente:

- Qualität Schaubilder (Legende, Überschrift, Visualisierung insgesamt, …) und Tabellen (Nachkommastellen, Beschriftung, …)
- Interpretation der Schaubilder und Tabellen / Ergebnisse nachvollziehbar? 
- Nennen Sie konkrete Stellen, um ihre Argumente zu unterstützen 
- Gehen Sie auf Struktur, Klarheit und Verständlichkeit ein

**Fragen für Sie:**

- Wenn Sie nach ihrem Feedback zu ihrer eigenen Projektarbeit zurückkehren dürften, was würden Sie ändern?


# Umfang des Review Reports

- Der Review Report sollte 1/2 bis maximal 1 Seite umfassen
- Er sollte im Fließtext verfasst sein, wobei Sie sich an der Beantwortung der vorherigen Fragen orientieren können
- Der Review Report sollte in die drei Blöcke **Zusammenfassung**, **Positive Aspekte**, **Kritikpunkte** unterteilt sein
- Er sollte _konstruktiv_ und _mit konkreten Verbesserungsvorschlägen_ verfasst werden
    - Konzentrieren Sie sich auf die 2-3 wichtigsten Punkte, die Ihnen auffallen. Sprechen Sie nicht jeden Grammatik- oder Rechtschreibfehler an, doch wenn die Ausarbeitung insgesamt schlecht geschrieben ist (viele Wiederholungen)
- Achten Sie darauf ihren Review Report am Ende _zu knitten_

# Subjektive Einschätzung der _eigenen_ Projektausarbeitung

In jedem Review Report erhalten Sie Fragen zu ihrer subjektiven Einschätzung der _eigenen_ Projektausarbeitung. Diese Fragen sollten Sie im sogenannten YAML-Header beantworten. Ihre Antworten können weder von ihren Teammitgliedern noch von der zu bewertenden Gruppe eingesehen werden. Sie erhalten nach dem 1. Projekt einen Muster-Review Report für dieses 1. Projekt um zu sehen, wie ein Review Report aussehen sollte und auch eine Erklärung, wie die Antworten im YAML Header eingefügt werden sollten.